### ISSUE TITLE
Group tags broken?

### ISSUE THREAD

**Issue by irsdl** [hackvertor/hackvertor#116]
This used to work before to have group tags in custom tags but now seems to be broken:
```
<@python('output = convert("<@replace(\'=\',\'\')><@base64>"+input+"<@/base64><@/replace>")','8c3513e66a03c52d293137e764ddcd54')><@/python>
```

The error is:
```
Invalid Python code:Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "<string>", line 14, in convert
NameError: global name 'hackvertor' is not defined
```

Am I doing something differently now?

**Comment by hackvertor** [comment]
I probably introduced a bug I'll try to fix it next release
