### ISSUE TITLE
uuid tag import does not work

### ISSUE THREAD

**Issue by Techbrunch** [hackvertor/hackvertor#117]
No sure what happened but the `uuid` tag cannot be imported, the `ip` tag works fine though.

The following error can be found in the extension tab:

```
java.lang.NullPointerException: Invocation type cannot be null
	at burp.Zfb8.Zb(Unknown Source)
	at burp.Zndw.getInvocationContext(Unknown Source)
	at burp.Zndw.getSelectionBounds(Unknown Source)
	at burp.BurpExtender.createMenuItems(BurpExtender.java:1611)
	at burp.Zfib.provideMenuItems(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zpxr.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy34.provideMenuItems(Unknown Source)
	at burp.Zm3y.ZB(Unknown Source)
	at burp.Znwf.ZQ(Unknown Source)
	at burp.Zyn.Zi(Unknown Source)
	at burp.Zyn.ZJ(Unknown Source)
	at burp.Zyn.Zw(Unknown Source)
	at burp.Zyn.ZV(Unknown Source)
	at burp.Za8g.Zg(Unknown Source)
	at burp.Zch5.ZZ(Unknown Source)
	at burp.Zna6.mousePressed(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6618)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6386)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by irsdl** [comment]
The `<@uuid/>` works fine for me in Windows installer version (latest EA). I think the best is to include more details of what tag / code you are running and in what OS.

**Comment by irsdl** [comment]
Sorry my bad, no I hadn't tried the one in the tag store. It does not install it for me either.

**Comment by Techbrunch** [comment]
>< I just realized that there was already an `uuid` tag in the Math category in Hackvertor thanks to your comment @irsdl. While there might still be a bug to fix I'm not sure there is still a need for a uuid tag in the store. The only difference with my code is that you can set the version (1 or 4).

**Comment by irsdl** [comment]
I think having the different version of uuid is good. I also like it even better if a uuid tag can generate one with all 0s too for some test cases.

**Comment by hackvertor** [comment]
This is fixed in the new release out shortly.
