### ISSUE TITLE
Hackvector fails to reinstall after being removed from extensions

### ISSUE THREAD

**Issue by DeathsPirate** [hackvertor/hackvertor#17]
I have a strange issue where I can't reinstall hackvector after removing from extensions and restarting burp.

It says it installed but it's definitely not.

**Comment by hackvertor** [comment]
Hiya DeathsPirate, thanks for the report. Please could you start the burp jar from the command line e.g.
java -jar burpsuite_pro.jar

See if you get a stack trace in the terminal and paste it in this issue. It might also be worth looking at the errors tab too. I did some work with the custom tags JSON and save it in the extension setting so this could potentially cause Hackvertor not to start.

**Comment by DeathsPirate** [comment]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by burp.adq (file:/home/ubuntu/BurpSuitePro/burpsuite_pro.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of burp.adq
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class javax.swing.Painter (java.lang.Boolean is in module java.base of loader 'bootstrap'; javax.swing.Painter is in module java.desktop of loader 'bootstrap')
	at java.desktop/javax.swing.plaf.nimbus.NimbusStyle.getBorderPainter(NimbusStyle.java:792)
	at java.desktop/javax.swing.plaf.nimbus.SynthPainterImpl.paintBorder(SynthPainterImpl.java:117)
	at java.desktop/javax.swing.plaf.nimbus.SynthPainterImpl.paintPanelBorder(SynthPainterImpl.java:975)
	at java.desktop/javax.swing.plaf.synth.SynthPanelUI.paintBorder(SynthPanelUI.java:190)
	at java.desktop/javax.swing.plaf.synth.SynthBorder.paintBorder(SynthBorder.java:63)
	at java.desktop/javax.swing.JComponent.paintBorder(JComponent.java:967)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1075)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:246)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1890)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by DeathsPirate** [comment]
Errors tab won't load.  It appears to hang.

**Comment by hackvertor** [comment]
Thanks, could you please scroll down to the first occurrence of BurpExtender and paste it here. It would help me find the problem in the code. Cheers!

**Comment by DeathsPirate** [comment]
That is the whole stack trace

**Comment by hackvertor** [comment]
It's hard to know the problem because I can't see the Hackvertor code responsible. Have you tried disabling every other extension apart from Hackvertor?

**Comment by DeathsPirate** [comment]
Yes, tried removing all other extensions and just having hackvector but get the same issue.
It installed fine the first time but after removing -> restarting burp -> installing I get nothing.  No errors in the logs, no output in the output tab, no "hackvector" tab on burp.  However it says it installed :/

**Comment by DeathsPirate** [comment]
Oh strangely it's just appeared

**Comment by DeathsPirate** [comment]
Yes all seems fine now, not sure why it would take nearly 30 mins to load the extension :/

**Comment by hackvertor** [comment]
Great! Glad it's working. If you get to the bottom of why it was taking too long to load let me know in this issue.

**Comment by DeathsPirate** [comment]
Will do, I'll close the issue but keep an eye on it.
