### ISSUE TITLE
Write a tag parser

### ISSUE THREAD

**Issue by hackvertor** [hackvertor/hackvertor#18]
The unique tag numbers are a source of great confusion. They are there because:

Here's a more detailed explanation.. If you use the following tags in HV:
`<@base64><@base64>test<@/base64><@/base64>`

You will get incorrect output because HV looks for the first closing tag and then matches it with the first opening tag, this then consumes the inner base64 tag. The resulting output will be:
`PEBiYXNlNjQ+dGVzdA==<@/base64>`

This is why I need a tag parser to ensure multiple tags of the same type can be used. I already have the regexes to match tag parameters. I just need a simple parser that will find the correct opening/closing tags and parse the parameters correct.

**Comment by CoreyD97** [comment]
Hey, mind if I take a shot at this issue? :)

**Comment by hackvertor** [comment]
You would be a legend if you did this and I would be forever grateful

**Comment by CoreyD97** [comment]
I'm already on it! :) Just had to refactor the codebase first to separate everything into separate files.
https://github.com/CoreyD97/hackvertor/commit/caff0d79dfd860527c5228a11fcd566ba4d84203

**Comment by hackvertor** [comment]
Brilliant thanks :) Yeah I was meaning to do that as well but never got round to it.

**Comment by irsdl** [comment]
Any update @CoreyD97 and @hackvertor ?

**Comment by CoreyD97** [comment]
I've been pretty busy since moving job roles, but it's in progress still. The basic tokenizer is built, but I need to add parameter support and the final parser.

**Comment by hackvertor** [comment]
Congrats with the new job! There's absolutely no rush on my side just whenever you have time but you will make a lot of people happy 😀

**Comment by CoreyD97** [comment]
Finally had a couple of days off recently, and decided to work on this a little bit. 
The parser is implemented, new conversion method works as far as my (admittedly limited) testing has gone. Might be a few little hiccups, I've not had to implement tail recursion in a couple of years :smile: 

There's still some little things I want to implement, such as allowing tags to have as many parameters as required, but it's in a mostly working state to be tested now. 

https://github.com/CoreyD97/hackvertor/tree/parser

CC @irsdl

**Comment by hackvertor** [comment]
Thanks so much I'll definitely test this when I have time. @irsdl please could you also test if you don't mind. Thanks again!

**Comment by hackvertor** [comment]
The tags look beautiful! Found a parsing error though:

<@base64><@base64>test<@/base64><@/base64>


<@hex( )><@base64><@base64>abc<@/base64><@/base64><@/hex>

Results in:
Error: Found closing tag "hex" without matching open tag.
burp.parser.ParseException: Found closing tag "hex" without matching open tag.
	at burp.Convertors.convert(Convertors.java:660)
	at burp.Convertors.convert(Convertors.java:669)
	at burp.Convertors.convert(Convertors.java:669)
	at burp.Convertors.convert(Convertors.java:669)
	at burp.Convertors.convert(Convertors.java:669)
	at burp.Convertors.convert(Convertors.java:669)
	at burp.Convertors.newConvert(Convertors.java:620)
	at burp.Hackvertor.convert(Hackvertor.java:346)
	at burp.ui.HackvertorPanel$4.insertUpdate(HackvertorPanel.java:144)
	at java.desktop/javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:203)
	at java.desktop/javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:757)
	at java.desktop/javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:716)
	at java.desktop/javax.swing.text.PlainDocument.insertString(PlainDocument.java:131)
	at java.desktop/javax.swing.text.AbstractDocument.replace(AbstractDocument.java:675)
	at java.desktop/javax.swing.text.JTextComponent.replaceSelection(JTextComponent.java:1339)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$TextTransferHandler.handleReaderImport(BasicTextUI.java:2459)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$TextTransferHandler.importData(BasicTextUI.java:2599)
	at java.desktop/javax.swing.TransferHandler.importData(TransferHandler.java:827)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$TextTransferHandler.importData(BasicTextUI.java:2537)
	at java.desktop/javax.swing.TransferHandler$TransferAction.actionPerformedImpl(TransferHandler.java:1763)
	at java.desktop/javax.swing.TransferHandler$TransferAction$1.run(TransferHandler.java:1712)
	at java.desktop/javax.swing.TransferHandler$TransferAction$1.run(TransferHandler.java:1710)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/javax.swing.TransferHandler$TransferAction$2.run(TransferHandler.java:1727)
	at java.desktop/javax.swing.TransferHandler$TransferAction$2.run(TransferHandler.java:1725)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.TransferHandler$TransferAction.actionPerformed(TransferHandler.java:1724)
	at java.desktop/javax.swing.text.JTextComponent.invokeAction(JTextComponent.java:1523)
	at java.desktop/javax.swing.text.JTextComponent.paste(JTextComponent.java:1501)
	at java.desktop/javax.swing.text.DefaultEditorKit$PasteAction.actionPerformed(DefaultEditorKit.java:1373)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
	at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2900)
	at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:2948)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2862)
	at java.desktop/java.awt.Component.processEvent(Component.java:6412)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:870)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1139)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4892)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by CoreyD97** [comment]
Ah, looks like it expects at least one parameter between the brackets. I'll make a little change to allow it to be empty and it should fix that issue!

**Comment by hackvertor** [comment]
Thanks again for your hard work!

**Comment by CoreyD97** [comment]
Should be fixed in https://github.com/CoreyD97/hackvertor/commit/90838945de9817eacb5134587d0ed3d5319e1e37.

I *think* the parser side of things is complete as of this commit. Let me know if you find any other issues in the meantime. I'll implement the additional changes I mentioned and remove the old code, then I think we should be good for a PR?

**Comment by hackvertor** [comment]
Fantastic! I'll give it another test and let you know

**Comment by hackvertor** [comment]
It's looking really good! There are a couple of bugs that I've found. Tags that have quotes, comma or a space in them are now not added correctly to the input. For example:
<@dec2hex(,)>255<@/dec2hex>

<@dec2bin(,)>255<@/dec2bin>

These should actually be (on the public HV):
<@dec2hex(",")>255<@/dec2hex>

<@dec2bin(",")>255<@/dec2bin>

Same with hex:
<@hex( )>test<@/hex>

Should be:
<@hex(" ")>test<@/hex>

Tag arguments with quotes in them aren't handling escapes correctly as well. For example:
<@hex("\"")>test<@/hex>  

Results in:
Error: Found closing tag "hex" without matching open tag.
burp.parser.ParseException: Found closing tag "hex" without matching open tag.
	at burp.Convertors.convert(Convertors.java:660)
	at burp.Convertors.convert(Convertors.java:669)
	at burp.Convertors.convert(Convertors.java:669)
	at burp.Convertors.newConvert(Convertors.java:620)
	at burp.Hackvertor.convert(Hackvertor.java:346)
	at burp.ui.HackvertorPanel$4.insertUpdate(HackvertorPanel.java:144)
	at java.desktop/javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:203)

Whereas on the public HV it results in:
74"65"73"74

Cheers

**Comment by CoreyD97** [comment]
Looks like the first issue was that I wasn't wrapping non-literal arguments in quotes. Should be fixed in the next push. Second issue was a bad string parser that couldn't handle escape sequences. Also fixed!

Also implemented a stub IBurpExtenderCallbacks class in the test module so you can run the Hackvertor extension outside of burp also. Useful for testing these kinds of things! :)

**Comment by CoreyD97** [comment]
Looks like the parser isn't happy about tag inputs ending in `<` characters at the minute, as it expects a following `@ ` to signify the start of a tag. Looking into a fix.
`<@html_entities>Taaest<<@/html_entities>`

**Comment by hackvertor** [comment]
Nice work! Looking forward to testing the new version. I guess with the < thing the parser could look ahead to see if there is a @ next. I chose @ when designing the tags because I thought it wouldn't be a common sequence.

**Comment by CoreyD97** [comment]
Turns out this was actually a surprisingly tough problem for me to figure out, but thanks to Christmas leave I've had a bit of time to work it out and have pushed another commit that should handle unfinished tags and treat them as text. Thankfully I enjoy debugging things like this and have learnt a lot in the process too :smile: 

One thing I noticed when comparing the output with the original Hackvertor implementation is that Hackvertor would treat unmatched tags as text. Is this an intentional choice? Or was it done to simplify the original parsing implementation? If you'd prefer, I can adjust the conversion method to work in the same way as opposed to flagging the unmatched tags.

If you want to give the new changes a try (if anybody is going to find bugs with the parser, it'll be you! :smile: ), [this](https://github.com/CoreyD97/hackvertor/commit/e53e7896be360bb7bc01fc24ad3a81f320a8b1d6) commit has the changes and the standalone Hackvertor test class I've been using to avoid having to load the whole of Burp each time.

**Comment by hackvertor** [comment]
Thanks so much for your hard work! My reasoning behind treating unmatched tags as text was in case the sequence wasn't a Hackvertor request and needed to be sent in a request. I'll give the build a try and let you know.

**Comment by CoreyD97** [comment]
No need for thanks, this is my version of fun :smile: That's sensible, I'll take a look at modifying the convertor method to work in the same way.

**Comment by CoreyD97** [comment]
Just made a quick copy of the convertor method that'll treat mismatched tags as text. This is the default mode now, but a toggle could always be implemented if for any reason somebody wanted to use the method with matching tag checks.
https://github.com/CoreyD97/hackvertor/commit/ca63926e95e5febf9ee045dabafce3b111161193

**Comment by hackvertor** [comment]
Cool thanks. I'll probably make it an option since you've already written the code :)

**Comment by hackvertor** [comment]
Hiya, Hmmm the escapes don't seem to be working. Eg.
IN: <@hex('\'')>ab<@/hex>
OUT: <@hex('\'')>ab<@/hex>

Also the variable tags are wrong. Variables are special in that when you set one it should still return its value. The reason for this is imagine you have a request smuggling request. You want to select part of the request and capture how many bytes it is but you also want to retain it's value. For example:

Parser Hackvertor:
IN: 
<@set_variable1>1<@/set_variable1>
<@get_variable1/>

Out: 

1

Old Hackvertor:
In:
<@set_variable1_1>1<@/set_variable1_1>
<@get_variable1_2 />

Out:
1
1

I'm conscious you've spent a lot of time on this so just let me know if you've had enough :)

**Comment by CoreyD97** [comment]
Thanks for the heads up, both of those should be an easy fix.

> I'm conscious you've spent a lot of time on this so just let me know if you've had enough

I don't think I'll ever get enough of programming, so no need to worry there.

**Comment by CoreyD97** [comment]
I'm assuming GitHub broke the escaped character in your comment, and have fixed the parser to allow escape sequences in strings like below:

|Input|Output|
|--|--|
|`<@hex('\'')>ab<@/hex>`|61'62|
|`<@hex("\"")>ab<@/hex>`|61"62|

https://github.com/CoreyD97/hackvertor/commit/2d420b133ea155aaf3020581bac875d2a53dcac0

---

Variable functionality also now matches the original implementation.
|Input|Output|
|--|--|
|`<@set_variable1>1<@/set_variable1> <@get_variable1/>`|`1 1`|
|`<@set('variable2')>2<@/set> <@get('variable2')/>`|`2 2`|

https://github.com/CoreyD97/hackvertor/commit/61622cc7d606b17b8aaea7b1cf2d56fd1d7a9d44

**Comment by hackvertor** [comment]
Nice work! Should be ready for a PR. Thanks again

**Comment by CoreyD97** [comment]
Awesome, thanks! Before I do, should I add to the parser so that it is backwards compatible with the old tag format e.g. <@base64_1>? Or is that counterproductive?

**Comment by hackvertor** [comment]
Nah it's not needed anymore and there was no way to save tags so I think we should be good

**Comment by hackvertor** [comment]
I've thought about it a bit and maybe it would be good to be backwards compatible for tags in blog posts etc sorry to mess you around.

**Comment by CoreyD97** [comment]
No problem, it's definitely better to have it in to make sure old examples from blogs don't get broken. I've implemented that https://github.com/CoreyD97/hackvertor/commit/2351fcbce3239e7d80c5138d98ba6f2fffc69afb .

During this I also noticed that I made a mistake in the `weakConvert` method, so inputs which ended while still having unclosed tags on the stack didn't add the tag as text to the output.
e.g.
|Input|Output|
|--|--|
|`<@base64>Test<@/base64><@hex>A`|`VGVzdA==A`|

After fix https://github.com/CoreyD97/hackvertor/commit/4c7423ff73f4a3066d04f5a36393988531296680
|Input|Output|
|--|--|
|`<@base64>Test<@/base64><@hex>A`|`VGVzdA==<@hex>A`|

**Comment by hackvertor** [comment]
Should be on the BApp store soon!
