### ISSUE TITLE
Hackvertor does not transform the request and fails with exception "Can't find the header"

### ISSUE THREAD

**Issue by nitram2342** [hackvertor/hackvertor#75]
I stumbled uppon an issue, where the Hackvertor did not transform Repeater requests anymore, but triggerd a "Can't find the header" exception when updating the Content-Length. Finally, it worked when I moved down the the Content-Length HTTP header line to be the last line in a HTTP header.

Environment and versions:
- Burp Suite Pro 2023.2.1 but also 2023.1.2 for WIndows 64bit
- Hackvertor v1.7.2
- Logger++ is loaded as the last module.
- Hackvertor and Logger++ are the only loaded extensions.
- Hackvertor's menu entry "Allow tags in *" is checked
- Hackvertor's menu entry "Allow update content length" is checked
- The Repeaters setting "Update Content-Length" is checked

Observations:
- There is an exception for the Hackvertor extension logged in the "Error" tab.
- Logger++ shows an untransformed request sent to the server.

Request example (a bit masked):

```
POST /XXXXXXXXXXXXX HTTP/1.1
Host: XXXXXXXXXXXXXXXX:XXXX
User-Agent: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Accept: */*
Content-Type:application/octet-stream
Content-Length: 622
Connection: close


<foo><@base64>XXXXX<@/base64></foo>
```

Exception:
```
java.lang.RuntimeException: Can't find the header
	at burp.BurpExtender.setHeader(BurpExtender.java:1056)
	at burp.BurpExtender.fixContentLength(BurpExtender.java:1010)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:1115)
	at burp.pme.handleHttpRequestToBeSent(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.j99.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy30.handleHttpRequestToBeSent(Unknown Source)
	at burp.nbv.J(Unknown Source)
	at burp.bwr.J(Unknown Source)
	at burp._e2.x(Unknown Source)
	at burp.qy5.f(Unknown Source)
	at burp.qy5.P(Unknown Source)
	at burp.qr7.P(Unknown Source)
	at burp.bct.P(Unknown Source)
	at burp.bgd.P(Unknown Source)
	at burp.b6t.p(Unknown Source)
	at burp.qai.p(Unknown Source)
	at burp.sej.I(Unknown Source)
	at burp.nrw.w(Unknown Source)
	at burp.p9j.x(Unknown Source)
	at burp.mga.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

It works, if the Request looks like this:

```
POST /XXXXXXXXXXXXX HTTP/1.1
Host: XXXXXXXXXXXXXXXX:XXXX
User-Agent: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Accept: */*
Content-Type:application/octet-stream
Connection: close
Content-Length: 622


<foo><@base64>XXXXX<@/base64></foo>
```

**Comment by hackvertor** [comment]
Thanks for the report!

This is fixed in Hackvertor v1.7.39. The bug was because the getOffsetHeaders method was looking a space to find the end of a header name. Your request contains a content-type header without a space after the colon, this resulted in the exception because the header name wasn't found.
